//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculator.Logic {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programs\\MVS2019\\Microsoft Visual Studio\\SaveFile\\EmployeeTimeJournal.csv")]
        public string PathToEmployeeJournal {
            get {
                return ((string)(this["PathToEmployeeJournal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programs\\MVS2019\\Microsoft Visual Studio\\SaveFile\\FreelancerTimeJournal.csv")]
        public string PathToFreelancerJournal {
            get {
                return ((string)(this["PathToFreelancerJournal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programs\\MVS2019\\Microsoft Visual Studio\\SaveFile\\HeadTimeJournal.csv")]
        public string PathToHeadJournal {
            get {
                return ((string)(this["PathToHeadJournal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Programs\\MVS2019\\Microsoft Visual Studio\\SaveFile\\AllEmployees.csv")]
        public string PathToAllEmployees {
            get {
                return ((string)(this["PathToAllEmployees"]));
            }
        }
    }
}
